# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI --Nome do script

on:
  pull_request:
    branches: [ "master"]

jobs:
  construcao:
    runs-on: ubuntu-latest
    name: construção da app
    steps:
      - uses: actions/checkout@v3
      - name: Configura o node 
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - run: npm i
      - run: npm run build
  deploy: 
    runs-on: ubuntu-latest
    name: deploy cd 
    needs: construcao
    steps: 
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: alexandremariano
          password: dckr_pat_XANoqz18avQR-v2aTk-xZ0bdvvA
    
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: alexandremariano/front-e-commerce
